name: selaras_backend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0 # Menggunakan versi stabil terbaru

dependencies:
  flutter:
    sdk: flutter
  # Pindah ke sini (sejajar dengan flutter:)
  supabase_flutter: ^2.8.1
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.1
  intl: ^0.19.0 #tanggal

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_splashscreen.png
    - assets/images/login_illustration.png